#! /bin/bash

check() {
    if [ $? = 0 ]
    then
        echo "[   OK ] $1"
    else
        echo "[ FAIL ] $1"
        exit 1
    fi
}

# 1. Test default execution

[[ "$(../pi)" =~ ^'{"pi":"3.'[0-9]+'","precision":3012,"time_ms":'[0-9]+\.[0-9]+\}$ ]]
check "Test default execution"
